### ISSUE TITLE
"ansible-vault not found using path in package settings."

### ISSUE THREAD

**Issue by sebamontini** [sydro/atom-ansible-vault#12]
just installed this package and i'm getting this error:
"ERROR: ansible-vault not found using path in package settings. Ansible-vault will be deactivate!"

and won't run

I've tried to configure ansible vault absolute path (which is actually the default one) but won't work either

**Comment by sydro** [comment]
I need to know atom version (and what os) and how you have installed ansible.

**Comment by sebamontini** [comment]
sorry forgot to add:
Atom 1.15.0 in macOS Sierra (10.12.3)

i'm running ansible 1.9.4 (installed via pip)

**Comment by sydro** [comment]
Ok, i make code compatible with atom >= 1.15. 
Please update package and try now.

**Comment by sebamontini** [comment]
updated, restarted atom, and still getting the same error

also, now the settings seems to be broken, no longer able to configure my pass-file path

**Comment by sydro** [comment]
Can you tell me what are the non-core packages in your atom? Probably is the same problem in issue #11

**Comment by sebamontini** [comment]
sure, only 7 non-core packages:
atom-jinja2 0.6.0
dash 1.7.1
git-plus 7.3.3
language-docker 1.1.7
language-terraform 0.7.5
linter-python-pep8 0.2.0
smart-tab-names 1.0.5

**Comment by sydro** [comment]
I'm testing atom v1.16 and v1.15 on sierra with your packages, but the ansible binary path box, in package settings, is always there. Maybe the theme doesn't render well settings tab. What is your atom themes? i'm using the default theme (atom dark and light), but without any results.

**Comment by sebamontini** [comment]
I'm also using the default theme with no other themes installed.
Really weird.
Will try to add some screenshot later on today

**Comment by sebamontini** [comment]
ok, i'm seeing the settings boxes again (i did an uninstall and install, instead of just updating the package to 0.5.0.

but I'm still seeing the error
<img width="604" alt="screen shot 2017-03-11 at 09 25 22" src="https://cloud.githubusercontent.com/assets/1847189/23823230/dae08b10-063c-11e7-96cb-c482eca343d0.png">

**Comment by sebamontini** [comment]
just, tried the v1.16 beta of atom and i'm getting the same error :(

**Comment by sebamontini** [comment]
i commented out the try-catch part where it validates the path (since I couldn't found a way to fix it)
```
/*
    try {
      var child = require('child_process');
      child.execSync(atom.config.get('ansible-vault.path') + ' view --version');
    } catch(e) {
      obj_utils.DisableAuto();
      obj_utils.notifyMessage(3,"","ERROR: ansible-vault not found using path in package settings. Ansible-vault will be deactivate!");
      this.deactivate();
      return
    }
*/
```
and now it's working fine, any ideas?

**Comment by sydro** [comment]
you don't comment that part. Try do change the code like this:

```
     /* obj_utils.notifyMessage(3,"","ERROR: ansible-vault not found using path in package settings. Ansible-vault will be deactivate!"); */

      obj_utils.notifyMessage(3,"","ERROR:" + e);
```

so we can see the error and not the default message.
Then past me the error here. Thanks

**Comment by sebamontini** [comment]
ok, seems like an issue with ansible 1.9.x and the way the plugin is validating if vault is there or not:
```
ERROR:Error: Command failed: /usr/local/bin/ansible-vault view --version Usage: ansible-vault view [options] file_name

ansible-vault: error: no such option: --version
```

**Comment by sydro** [comment]
I pushed now a new check with "--help" option and not with "--version". It works with ansible 1.9.x and later.
Please try new release and tell me if it's ok :) 
Thanks for help!

**Comment by sydro** [comment]
Can i have your feedback? so i can close this issue :+1:

**Comment by sebamontini** [comment]
the fix worked great, everything seems to be working fine for now.

THANKS!

**Comment by Akilij24** [comment]
I'm having the same issue with the error:
ERROR: ansible-vault not found using path in package settings. Ansible-vault will be deactivate!
Error: Command failed: /usr/local/bin/ansible-vault --help The system cannot find the path specified.
Running on a Windows computer / running atom version 1.15.0 x64

**Comment by sebamontini** [comment]
maybe in windows ansible-vault is located in a different path, you should be able to change it in the plugin settings

**Comment by sydro** [comment]
@sebamontini said right. You must configure ansible-vault path in settings package, the error message is clear: "The system cannot find the path specified". This is not bug.

**Comment by cmfrtl** [comment]
ERROR: ansible-vault binary not found. Probably need to configure the absolute path in settings. After change the path you need to disable and enable package again! Check the reference: https://github.com/sydro/atom-ansible-vault.

Ansible-vault package will be deactivated!

ERROR! Missing required action

$ cat /etc/issue
Ubuntu 16.04.3 LTS \n \l

$ ls /usr/bin/ansible-vault
/usr/bin/ansible-vault

Settings:
Ansible Vault absolute path: /usr/bin/ansible-vault
