### ISSUE TITLE
Absolute path error

### ISSUE THREAD

**Issue by Akilij24** [sydro/atom-ansible-vault#14]
I'm receiving this error after installing "ansible-vault" for Atom-
ERROR: ansible-vault not found using path in package settings. Ansible-vault will be deactivate!

Error: Command failed: /usr/local/bin/ansible-vault --help The system cannot find the path specified.

I'm using a remote computer that is not the Ansible server

**Comment by sydro** [comment]
This is not bug, you must install ansible on computer and configure binary path in package settings tab.
