### ISSUE TITLE
Python 3

### ISSUE THREAD

**Issue by certifiedloud** [sydro/atom-ansible-vault#15]
Use __future__ to make this package support python 2.x and 3.x simultaneously.
The print statements in the python files cause this to fail on systems that use python 3 by default.

**Comment by kinnarr** [comment]
It's also possible to use `#!/bin/env python2` instead of `#!/bin/env python` in lib/bin/vault_wrapper.py.

**Comment by cinemast** [comment]
Could the shebang be changed? The package is currently unusable in arch linux.

**Comment by sydro** [comment]
does this `#!/bin/env python` shebang not work in arch linux?

**Comment by kinnarr** [comment]
In arch linux python 3 is the default, so `#!/bin/env python` resolves to python3 instead of python2

**Comment by cinemast** [comment]
That is exactly the problem. If you require python2 please also specify python2 in the shebang. @sydro could you fix this please and prepare a new release?

**Comment by sydro** [comment]
@cinemast i fix shebang to `#!/usr/bin/env python2` to restore wrapper with python2 in 5710987 commit  . i'm working to made it compatible with python3.
Thanks

**Comment by sydro** [comment]
I removed the python libs dependencies. Now en/decrypter is only javascript, and it call ansible-vault binary.
