### ISSUE TITLE
This package added 398ms to startup time

### ISSUE THREAD

**Issue by xenithorb** [sydro/atom-ansible-vault#16]
Kind of nit-picky but is there a reason this needs to be the worst offending package in timecop? It doesn't seem to need to do much on startup, so that makes me inclined to think it's broken somehow. 

![image](https://cloud.githubusercontent.com/assets/10273878/25799120/d3186748-33b1-11e7-8a99-ffc1d51ecf55.png)

Note the second column on the bottom, it is the slowest package by a whole 175ms!

**Comment by sydro** [comment]
Hi, i found the problem. it is this syncronous check that blocks execution.
>       child.execSync(atom.config.get('ansible-vault.path') + ' --help');

I will change this line with an async promise to solve slow startup.
Thanks!

**Comment by xenithorb** [comment]
Nice work!

**Comment by sydro** [comment]
I changed the check in commit  74fec0e. I thinks that now is more efficient.
![schermata del 2017-05-08 20 39 20](https://cloud.githubusercontent.com/assets/888356/25819890/b34a7cb6-342f-11e7-8b25-c1efdbdd625a.png)
