### ISSUE TITLE
Auto encrypt fails on single-click to open file

### ISSUE THREAD

**Issue by jhkrischel** [sydro/atom-ansible-vault#18]
I can only seem to get auto-encrypt working if I double-click a file - if I single-click in the navigator, it will open a tab, but when that tab is closed, it won't auto-encrypt:

single click vault file - auto decrypted
close vault file (Command-W) - still decrypted

double click vault file - auto decrypted
close vault file (Command-W) - auto encrypted

**Comment by sydro** [comment]
I confirm this bug. In the new atom version something was change. I'm trying to fix.

**Comment by sydro** [comment]
I fixed it!
Thanks!

**Comment by jhkrischel** [comment]
Beautiful, just tested, very happy!
