### ISSUE TITLE
Cannot find password file

### ISSUE THREAD

**Issue by jsumners** [sydro/atom-ansible-vault#20]
Attempting to use the feature from #9 I am getting an error: "ERROR! The vault password file /vault.pass was not found".

As described in #9, my `ansible.cfg` looks like:

```
[defaults]
vault_password_file = vault.pass
```

And `vault.pass` is a sibling file to `ansible.cfg` in the root directory of a project.

**Comment by sydro** [comment]
Hi, i fixed it.
Thanks

**Comment by jsumners** [comment]
Awesome! It's working great now. Thank you very much.
