### ISSUE TITLE
Don't require ansible-vault

### ISSUE THREAD

**Issue by AlexAkulov** [sydro/atom-ansible-vault#21]
Hello! 

I use VS Code on Windows for writing ansible playbooks but ansible-vault doesn't work on windows and every time I have to checkout playbooks on my Linux VM for editing secrets. This plugin would help me a lot but it requires ansible-vault too. 
I know that ansible-vault uses simply AES algorithm for encrypting and decrypting data. I think that it may be realized in this plugin on pure js without requiring ansible-vault. Probably npm has many libraries for cryptography with AES256 support.

**Comment by sydro** [comment]
Hi, this is a good idea, but i don't want to remove ansible-vault dependency. Changes in my packages will not be needed, if ansible developers will introduce new features or new encryption algorithm.
Sorry, i can't help you with your problem. I suggest you to run ansible-vault on cygwin to fix your problem on windows without use Linux VM.
