### ISSUE TITLE
[ERROR] ansible-vault "command not found"

### ISSUE THREAD

**Issue by ecwpz91** [sydro/atom-ansible-vault#22]
# Problem

Path name resolution for _Ansible Value absolute path_ default package setting, `/usr/local/bin/ansible-vault`, does not exist.

# Message

```sh
ERROR: ansible-vault not found using path in package settings. Ansible-vault will be deactivate!

/bin/sh: /usr/local/bin/ansible-vault: No such file or directory
```

# Bypass

1. Create [symlink][2] to missing reference file:

```sh
# ln -s /usr/bin/ansible-vault /usr/local/bin/ansible-vault
```

2. Manually update Atom [package settings][3].

# Release

- Atom release 1.18.0; see [installation][1].
- `cat /etc/os-release` is as follows:

```sh
NAME=Fedora
VERSION="26 (Workstation Edition)"
ID=fedora
VERSION_ID=26
PRETTY_NAME="Fedora 26 (Workstation Edition)"
ANSI_COLOR="0;34"
CPE_NAME="cpe:/o:fedoraproject:fedora:26"
HOME_URL="https://fedoraproject.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=26
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=26
PRIVACY_POLICY_URL=https://fedoraproject.org/wiki/Legal:PrivacyPolicy
VARIANT="Workstation Edition"
VARIANT_ID=workstation
```

[1]: https://fedoramagazine.org/install-atom-fedora/
[2]: https://en.wikipedia.org/wiki/Symbolic_link
[3]: http://flight-manual.atom.io/using-atom/sections/atom-packages/#package-settings

**Comment by sydro** [comment]
Hi, this is not a bug. You need set ansible-vault binary path in package settings. Let see screenshot https://raw.githubusercontent.com/sydro/atom-ansible-vault/master/images/screenshot-settings.png.

**Comment by ecwpz91** [comment]
Yes. I already said that under `Bypass` section above. 

But, I could've been better about explaining my situation.

This happens during _first-time_ installation.

My immediate experience after downloading was, pop-up - "ERROR".

How do I know if this is expected behavior or not?

In fact, my initial response was: "This package is broken. Uninstall."

Since I value your tool, my suggestion(s) are:

1. Check for [Cross-Platform Compatibility][1], and use this to handle setting the default `Ansible Value absolute path` to a valid reference file location on target environments.
2. Document expected behavior of all configurable settings.

[1]: http://flight-manual.atom.io/hacking-atom/sections/cross-platform-compatibility/#cross-platform-compatibility

**Comment by ecwpz91** [comment]
You could [label][1] this as an "enhancement" as well? 

Anyway, hope that helps clarify some things.

[1]: https://guides.github.com/features/issues/#filtering

**Comment by sydro** [comment]
Thanks, i think that i will change the error message with settings reference.

**Comment by sydro** [comment]
I changed the error message with reference to this repository and updated the README.md with little description of any thing that you can set.

**Comment by ecwpz91** [comment]
+1, looks great. Thanks! On a side note, you may want to add documentation [guidelines for repo contribution][1] in case I, or someone else, would like to issue a new statement in the future.

[1]: https://help.github.com/articles/setting-guidelines-for-repository-contributors/

**Comment by sydro** [comment]
I added CONTRIBUTING.md file with essential guidelines as you suggested! Thanks :+1:
