### ISSUE TITLE
Plugin seems broken

### ISSUE THREAD

**Issue by jeroen-s** [sydro/atom-ansible-vault#23]
Atom version: 1.20.1
ansible-vault version: 0.6.5
Ansible version: 2.3.2.0 (installed via brew)

Config:
```
  "ansible-vault":
    vault_automatic_de_and_encrypt: true
    vault_password_file_forcing: true
    vault_password_file_path: "~/.secrets/vault_pass.txt"
```

Observations:
- Automatic encryption/decryption is not performed (no errors).
- Manually toggling produces a prompt for the vault pass. When I provide it, decryption works, but a second prompt appears right after.

I have tried re-installing the plugin and moving the password file

**Comment by sydro** [comment]
Hi, i problably found the bug. I made a fix in version 0.6.6. Can you verify that it works again?

**Comment by jeroen-s** [comment]
Thanks for the update! This indeed fixes the auto encrypt/decrypt part of the issue. However, I'm still getting prompted for the vault password despite setting the password file path (see above).

**Comment by sydro** [comment]
Another version is out! :+1: v0.6.7

I hope that the problem is fixed.

**Comment by jeroen-s** [comment]
everything seems to work, thanks for the quick response!

**Comment by sydro** [comment]
Thank you! :+1:
