### ISSUE TITLE
Error in ansible 2.4 when vault_password_file is definied

### ISSUE THREAD

**Issue by zenathar** [sydro/atom-ansible-vault#27]
in ansible 2.4 there is a possibility to use multiple vault keys. As a result, when vault_password_file is defined in ansible.cfg, encrypting fails with following error:

```
ERROR! Only one --vault-id can be used for encryption. This includes passwords from configuration and cli.
```

The easiest fix is to call encrypt function without ` --vault-password-file` parameter when vault_password_file or vault_identity is defined.

**Comment by jmooo** [comment]
Just ran into this, decryption works fine but then you get the above error on trying to re-encrypt

**Comment by gio-salvador** [comment]
I got a different error, not sure it's related:

ERROR! Decryption failed (no vault secrets would found that could decrypt) on /PATH/TO/VARFILE/vault_NAME.yml for /PATH/TO/VARFILE/vault_NAME.yml

**Comment by triplepoint** [comment]
any ideas on this one? Still happening at least as of today.
