### ISSUE TITLE
Silently failing

### ISSUE THREAD

**Issue by aioue** [sydro/atom-ansible-vault#29]
Been using regularly for month, now vault:toggle from menu does nothing. No warnings/errors on screen.

Plugin: 0.6.9
Atom: 1.23.1

Happy to debug with instructions.

**Comment by sydro** [comment]
Hi, 
I'm testing plugin with the same your configuration, but the toogle from menu works fine.
Can you try to reinstall plugin?

**Comment by ddrazyk** [comment]
Hi @sydro,
I'm having the same issue. Reinstalling the plugin doesn't seem to help. Nothing also shows up in dev console.
However it seems to be connected with the option "Use vault password file defined in ansible.cfg project". In ansible.cfg I have it set to relative path and it doesn't work. As soon as I turn the option off I get a prompt for vault password.

Plugin: 0.6.9
Atom: 1.23.2-0.1.x86_64 (Fedora RPM)

**Comment by sydro** [comment]
hi, 
can i ask what version of ansible you're currently using?
Thanks

**Comment by ddrazyk** [comment]
Hi @sydro,
it's ansible 2.4.2.0.

Cheers

**Comment by aioue** [comment]
![image](https://user-images.githubusercontent.com/1254905/34832649-650331c8-f6e5-11e7-8bda-4115a224acbd.png)

Atom vault plugin password set to `~/some/file`.

`ansible.cfg` contains `vault_password_file = ../../relative/path/file`.

Reinstalling did not help.

Ansible `2.4.2.0`.

**Comment by nmartinez-nimeops** [comment]
Same with ansible 2.3.1.0 and 2.4.2.0 :(

**Comment by nmartinez-nimeops** [comment]
no update?

**Comment by aioue** [comment]
Still failing on Atom `1.23.3`. @sydro I'm very happy to support any testing you need for this, let me know what you need.

**Comment by nmartinez-nimeops** [comment]
same withe atom 1.24

**Comment by nmartinez-nimeops** [comment]
same with ansible ansible 2.4.3.0
:(

No chance to fix it?

**Comment by l00v3** [comment]
I also have the same problem. Would be great to fix this, it's annoying now, as we used this in our work flow.
Ansible 2.4.1.0
Atom 1.24
Plugin 0.6.9

**Comment by sydro** [comment]
Hi,
sorry for my silent, i was very busy. 
I tried to reproduce the bug and i discovered that ansible produce this problem.
In the new version (>=2.4) you need ansible.cfg in the same directory where ansible-vault command runs. My package runs this command in the project root, so if ansible.cfg is in subdirectory de/encryption doesn't work. 
In the past i used "--vault-password-file" reading vault_password_file from ansible.cfg, but ansible gives priority to cfg file.
So i think that only solution is to force user to insert ansible.cfg in project root directory, with an alert/message.

Can you try this scenario for conferm my suppositions?

**Comment by nmartinez-nimeops** [comment]
hi,
not good.

Tried vault-password-file and ansible.cfg outside project dir, inside... :(

**Comment by sydro** [comment]
Hi, 
i added the possibility to use ansible.cfg in project directory or file directory. The packages looks for ansible.cfg in file path and after in project directory to try de/encrypt.

Thanks

**Comment by nmartinez-nimeops** [comment]
KO for me:
No ansible.cfg file found.
Disable flag in preferencies or add ansible.cfg file

ansible.cfg is in basedir.

**Comment by sydro** [comment]
Can you send me files list of directory ? 
The ansible.cfg must be in **project root** or in vault file directory.

**Comment by nmartinez-nimeops** [comment]
.
├── deploy_platform
│   ├── ansible.cfg
│   ├── data
│   ├── group_vars
│   ├── host_vars
│   ├── inventories
│   ├── plugins
│   ├── Readme.md
│   └── roles
└── vault_passwd

In ansible.cfg: 
vault_password_file = ../vault_passwd

**Comment by sydro** [comment]
I recreated your scenario with this configuration, but package works fine. What is it yours?

```
.
├── deploy_platform
│   ├── ansible.cfg
│   ├── data
│   ├── group_vars
│   └── host_vars
│       ├── subdir
│       │   ├── vaulted2.yml
│       │   └── vaulted3.yml
│       └── vaulted.yml
└── vault_passwd
```
ansible-vault 2.4.3.0 (installed via pip)
node v8.10.0
atom-ansible-vault 0.6.10
atom 1.24.1
ubuntu 16.04

Package configuration:
* Enable automatic de- and encrypt : **checked**
* Use vault password file defined in ansible.cfg project : **checked** 
* Use specific vault password file: **NO checked**

ansible.cfg contains:
```
[defaults]
vault_password_file=../vault_passwd
```

**Comment by nmartinez-nimeops** [comment]
ansible 2.4.3.0
atom-ansible-vault 0.6.10
atom 1.25.0
ubuntu artful

Always:
 No ansible.cfg file found.
Disable flag in preferencies or add ansible.cfg file

**Comment by sydro** [comment]
I tested with your config, but i haven't problems.

ansible 2.4.3.0
atom-ansible-vault 0.6.10
atom 1.25.0

I do not think the problem is caused by the package. Can you try to move ansible.cfg in the directory with vaulted file? If so it works, maybe the problem is the ansible.cfg location. 

I open the directory like as in screenshot attached.
![screenshot](https://user-images.githubusercontent.com/888356/37797979-b6cfdec6-2e1b-11e8-9373-cc0dd10cd72b.png)

**Comment by nmartinez-nimeops** [comment]
vault file is in upper directory
If i move ansible.cfg file, ansible-playbook won't work no?

**Comment by ddrazyk** [comment]
@nimeops it shouldn't break ansible as it gives preference to ansible.cfg which is located in your current working directory. My setup looks like the example by @sydro with additional sub-projects. 
Placing an ansible.cfg from @sydro example in the upper most branch solves all issues with automatic de-/encryption and doesn't break my ansible flow.
Thanks @sydro.

**Comment by sydro** [comment]
Thanks @ddrazyk for your test :+1:

**Comment by nmartinez-nimeops** [comment]
If ansible.cfg not on basedir where we execute ansible, the default is used, which is bad: 
config file = /etc/ansible/ansible.cfg

**Comment by sydro** [comment]
Hi @nimeops 
i changed the package. Now, it does a reverse recursive research of ansible.cfg file starting from vaulted pathfile. Tell me if this resolves your problem. Thanks

**Comment by nmartinez-nimeops** [comment]
Perfect!
Thank you :)

**Comment by aioue** [comment]
@sydro This is working for me now 🎉
