### ISSUE TITLE
Security issue

### ISSUE THREAD

**Issue by helldorado** [sydro/atom-ansible-vault#30]
After vault encrypt, cmd+z must never give the unencrypted version of the file.

Hope flushing the electron undo buffer for the related file can solve this issue.

Thank's for this packages ;-)

**Comment by brandonkal** [comment]
I can reproduce this. Hope this can be fixed.

There is also the issue that if you save the file when it is unencrypted, it will be saved in the same place. So by using this plugin, you are not directly using ansible-vault it seems. For instance, running
```
ansible-vault edit main.yml
```
It opens in vim at this path:

```
/var/folders/l2/.../tmpeyd0_kez.yml
```

There is also the issue of re-encryting the file... you are actually setting a new password, so if you mistype here, you will be locking yourself out (no confirm prompt).

**Comment by brandonkal** [comment]
An arguably more secure approach would be to use ansible-vault directly. To open the file in atom you would do this in the terminal:

```
EDITOR="/Applications/Atom.app/Contents/MacOS/Atom -w" ansible-vault edit vars/main.yml
```

If there was an atom package that could add this terminal command to the file context menu in atom and this could be called from an atom command, that would seem ideal.

The workflow would look like this:
1. Open file in atom.
2. Use command pallet or atom shortcut e-g- cmd-opt-0
3. File opens in new tab. Save at will and close tab when done.

**Comment by sydro** [comment]
Hi,
i fixed the plugin with clearing undo stack after encryption. 
Thanks!

**Comment by helldorado** [comment]
@sydro thank's for this update. Fixed for me.

**Comment by brandonkal** [comment]
Awesome. Is the clear of undo for the vaulted file or all files in the project?

**Comment by sydro** [comment]
Only vaulted file that you are working on!
