### ISSUE TITLE
Automatic encrypt stopped working in 0.7.0

### ISSUE THREAD

**Issue by andygeorge** [sydro/atom-ansible-vault#34]
I receive a "ENCRYPT: OK" message, but the file is saved in unencrypted plaintext. Manual encrypting works.

This is on Atom 1.30.0 on macOS 10.13.6.

**Comment by sydro** [comment]
I think that it's ok now. 
Thank you for issue!

**Comment by andygeorge** [comment]
Awesome, it works again, thanks!!
