### ISSUE TITLE
Decrypted files are empty

### ISSUE THREAD

**Issue by intonet** [sydro/atom-ansible-vault#37]
**Describe the bug**
After decryption files are empty

**To Reproduce**
1.select file
2. ctr+alt+0
3. enter password
4. file is empty

**Expected behavior**
See content of file.

**Desktop (please complete the following information):**
 - Atom version  1.32.2 
 - Ansible  2.6.4
 - OS: Mac OS X 10.14.1 
**Additional context**

Stop working e few days ago. Uninstall and install add-on again not fix problem. 
Decryption using ansible-vault work ok.

**Comment by sydro** [comment]
Hi @intonet 
i test it with atom 1.32, mac osx 10.14 and last ansible build on single file and it works.

Can you tell me your project directory structure and the settings of ansible-vault package?

Thanks

**Comment by intonet** [comment]
Hi
I made a video. 
https://youtu.be/IRFH8f73pDQ <https://youtu.be/IRFH8f73pDQ>
Package was reinstalled but nothing change.
Thanks

**Comment by sydro** [comment]
Hi, 
with atom 1.32.2 without other packages, mac osx 10.14 (on x64) and ansible 2.6.4, i can't reproduce the bug. 
Can you tell me the list of other (Non-Core) packages installed in atom ? and how did you install ansible (pip/brew)?

Thanks for your help

**Comment by intonet** [comment]
Hi
I have 
git-time-machine 2.1.0
Platformo-ide-terminal 2.8.4
Split-diff 1.5.3

I used pip to install ansible. 
Regards.

**Comment by sydro** [comment]
Hi,
i added a few changes on the package.
Can you try now and tell me if it's ok?

Thanks

**Comment by intonet** [comment]
Hi
Unfortunately still the same.

**Comment by sydro** [comment]
Please, can you try again ? sorry for the trouble :(

**Comment by intonet** [comment]
No problem
And this time it is work again. 
Thanks a lot man!

**Comment by sydro** [comment]
Wonderful! :+1:  Thanks you!!!
