### ISSUE TITLE
ansible-vault not found when running from git checkout

### ISSUE THREAD

**Issue by aioue** [sydro/atom-ansible-vault#4]
When running ansible from a git checkout (rather than installing via pip etc), `atom-ansible-vault` cannot find the executable.

Possible fix:
Add option to specify ansible path in package settings.

**Comment by sydro** [comment]
ansible path value added in package settings and created workaround to use ansible-vault binary instead python lib if not exists

Thanks 

Fixed in commit  fd79c83
