### ISSUE TITLE
The vault-ids default,default are available to encrypt. Specify the vault-id to encrypt with --encrypt-vault-id

### ISSUE THREAD

**Issue by usscarter** [sydro/atom-ansible-vault#40]
**Describe the bug**
When attempting to vault a file you are greeted with:
The vault-ids default,default are available to encrypt. Specify the vault-id to encrypt with --encrypt-vault-id

**To Reproduce**
Attempt to vault a file.

**Expected behavior**
Vaulting
**Desktop (please complete the following information):**
 - Atom version 1.33
 - Ansible version 2.6.3
 - OS: OSX Mojave

**Additional context**

**Comment by sydro** [comment]
Hi, this is not package bug. 
You can find more info here: https://github.com/ansible/ansible/issues/46310
