### ISSUE TITLE
Decryption fail and file deletion

### ISSUE THREAD

**Issue by ghost** [sydro/atom-ansible-vault#43]
**Describe the bug**

When the file is closed to encrypt it again, the following error appears and the file is deleted

**To Reproduce**
1. Enable automatic de- and encrypt
2. Open the file (DECRYPT OK)
3. Close the file
4. See error in the pop-up window

[0;31mERROR! The vault-ids default,default are available to encrypt. Specify the vault-id to encrypt with --encrypt-vault-id[0m

**Expected behavior**
Encrypt the file

**Desktop (please complete the following information):**
 - Atom version 1.37
 - Ansible version 2.7.7
 - OS: OSx Mojave

**Comment by beasteers** [comment]
Can confirm this is still a problem. 😕

Edit: it seems like this is an ansible issue https://github.com/ansible/ansible/issues/46310 and not actually a problem with this package, but I have to say it's pretty jarring to save your vault file and have it vanish.
