### ISSUE TITLE
ERROR: ansible-vault binary not found macOS

### ISSUE THREAD

**Issue by jakubmuransky** [sydro/atom-ansible-vault#44]
Path is correct, atom version 1.43.0. Could you please help me with that ? 
ERROR: ansible-vault binary not found. Probably need to configure the absolute path in settings. After change the path you need to disable and enable package again! Check the reference: https://github.com/sydro/atom-ansible-vault.
Ansible-vault package will be deactivated!

**Comment by jakubmuransky** [comment]
I find the path in **ansible-vault --version** then it works.

**Comment by jmooo** [comment]
I ran into this issue on macOS w/ Atom 1.45.0 and atom-ansible-vault 0.7.8 but it appears to have been because I was using a slightly older version of ansible (installed via `brew`):
```
$ ansible-vault  --version
dyld: Library not loaded: @executable_path/../.Python
  Referenced from: /usr/local/Cellar/ansible/2.9.2_1/libexec/bin/python3.8
  Reason: image not found
[1]    34632 abort      ansible-vault
```

updating to ansible 2.9.6_1 cleared the issue
