### ISSUE TITLE
Input dialog doesn't seem to recieve the password

### ISSUE THREAD

**Issue by fotisp** [sydro/atom-ansible-vault#5]
Can't seem to decrypt the file on OSX 

Getting the following error:

/home/user/.atom/packages/ansible-vault/lib/bin/vault_wrapper.py", line 66, in binary_mode() TypeError: binary_mode() takes exactly 1 argument (0 given)

I am copying and pasting the password if this makes any difference to the input dialog

Using the ansible vault file solves the problem, but it is an ugly workaround

**Comment by sydro** [comment]
There was a error in binary_mode function definition. I fixed it.
With the addiction of path ansible-vault setting in previous commit, you need to set it in package preferences.

Thanks
