### ISSUE TITLE
automatic de- and encrypt on open and save

### ISSUE THREAD

**Issue by telepath** [sydro/atom-ansible-vault#6]
We would like to ensure that no decrypted vault files are committed to repositories.
It would be great if the vault files content was automatically decrypted on file open, and encrypted on file save.

Would this be possible to implement in this plugin?

**Comment by sydro** [comment]
Sure! I think it's a good idea. 

I will develop the feature on open and close buffer file (not save). You'll be able to activate it with a flag in the settings tab.

**Comment by sydro** [comment]
Hi, 
i added a new flag in settings tab to enable and disable automatic de- and encryption of ansible vault files.
it works with a global vault password file and with manual password too.

Thanks for the issue ;)
