### ISSUE TITLE
Support for single encrypted variables

### ISSUE THREAD

**Issue by rarguelloF** [sydro/atom-ansible-vault#8]
It would be nice to support this feature: http://docs.ansible.com/ansible/playbooks_vault.html#single-encrypted-variable

Tell me if you think it's feasible and I could help you with a PR.

Thanks! :D

**Comment by sydro** [comment]
Hi, 
ansible v2.3 will be release soon and i think that it's an interesting feature. If you want create a PR, i will  appreciate it! :+1: 
we can discuss together how to implement it, if you need it.

Thanks for help!!!

**Comment by jdoss** [comment]
I just found out about this feature in Ansible 2.3. It would be super awesome if you could:

1) highlight the text you wanted to encrypt  
2) hit a hotkey or toggle the ansible-vault command via the right click dialog to encrypt it 

or maybe this as well, just search for lines that have `!vault |` and encrypt/decrypt the text after it for the whole document. 

As of right now I have a file that I just put the encrypted text into and I use the right click dialog to encrypt it and I copy it back into my playbook. Pretty clunky workflow to use this feature.

**Comment by kyle-williams-1** [comment]
See if PR#33 solves your issue 
https://github.com/sydro/atom-ansible-vault/pull/33
