### ISSUE TITLE
Read vault pass from configured pass file

### ISSUE THREAD

**Issue by jsumners** [sydro/atom-ansible-vault#9]
This plugin should read the password for the encrypted file from the configured password file. For example, with the following structure:

```
project
|
-- vars/
    |
    -- secrets.yml
|
-- ansible.cfg
-- playbook.yml
-- valut.pass
```

Where `ansible.cfg` contains:

```
[defaults]
vault_password_file = vault.pass
```

Then opening `vars/secrets.yml` should prompt the plugin to traverse the directory tree upward until it finds `ansible.cfg`. It should then read `ansible.cfg` to learn that the password is in `vault.pass` and read the password from that file.

**Comment by dnmvisser** [comment]
In addition, the plugin should pick up the `ANSIBLE_VAULT_PASSWORD_FILE` environment variable - see http://docs.ansible.com/ansible/playbooks_vault.html#running-a-playbook-with-vault.

**Comment by jmooo** [comment]
This would be fantastic, as I could separate the password from my work and personal ansible projects

**Comment by sydro** [comment]
Hi, i created a new release. Now the package reads project ansible.cfg to define vault password file.
Thanks for the request! :ok_hand:

**Comment by jsumners** [comment]
Thank you.
